api_login_check:
  path: /api/login_check
sets:
  # loads routes from the YAML, XML or PHP files found in that directory
  resource: '../src/Sets/Infrastructure/Symfony/config/'
  prefix: '/api'
  type:     directory

register_user:
  path: /register
  controller: PowerNav\User\Infrastructure\Controller\UserRegisterPostController
  methods: [POST]

users:
  # loads routes from the YAML, XML or PHP files found in that directory
  resource: '../src/User/Infrastructure/Symfony/config/'
  prefix: '/api'
  type:     directory

