version: "3"
services:
  php:
    container_name: powernav_php
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./etc/docker/Dockerfile
    volumes:
      - ./:/var/www/xperales

  postgres:
    container_name: powernav_postgres
    image: postgres:12-alpine
    restart: always
    env_file:
      - .env.database # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5455:5432

  nginx:
    container_name: powernav_nginx
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./:/var/www/xperales
      - ./etc/docker/nginx/manhattan.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php
      - postgres
volumes:
  database-data:
