doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            set_id: PowerNav\Sets\Infrastructure\Persistence\Doctrine\SetIdType
            rpe: PowerNav\Sets\Infrastructure\Persistence\Doctrine\RPEType
            weight_unit: PowerNav\Sets\Infrastructure\Persistence\Doctrine\WeightUnitType
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Sets:
                type: xml
                prefix: PowerNav\Sets\Domain
                dir: '../../../src/Sets/Infrastructure/Persistence/Doctrine'
                is_bundle: false
